project_name: example
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
nfpms:
- maintainer: Reddy <root@reddy.dev>
  description: Sample project.
  homepage: https://github.com/reddyduggempudi
  license: MIT
  formats:
  - zip